# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/courses/University courses/Design Automation/Homeworks/HW5/codes/codes.cache/wt} [current_project]
set_property parent.project_path {D:/courses/University courses/Design Automation/Homeworks/HW5/codes/codes.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/courses/University courses/Design Automation/Homeworks/HW5/codes/codes.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{D:/courses/University courses/Design Automation/Homeworks/HW5/codes/codes.srcs/sources_1/new/arbiter.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top arbiter -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef arbiter.dcp

catch { report_utilization -file arbiter_utilization_synth.rpt -pb arbiter_utilization_synth.pb }
