# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/courses/University_courses/Design_Automation/project/project_2/project_2.cache/wt [current_project]
set_property parent.project_path E:/courses/University_courses/Design_Automation/project/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  E:/courses/University_courses/Design_Automation/project/project_2/project_2.srcs/sources_1/imports/code/full_adder.vhd
  E:/courses/University_courses/Design_Automation/project/project_2/project_2.srcs/sources_1/imports/code/multiplier.vhd
  E:/courses/University_courses/Design_Automation/project/project_2/project_2.srcs/sources_1/imports/code/BinaryToBCD.vhd
  E:/courses/University_courses/Design_Automation/project/project_2/project_2.srcs/sources_1/imports/code/half_adder.vhd
  E:/courses/University_courses/Design_Automation/project/project_2/project_2.srcs/sources_1/imports/code/BCD_multiplier.vhd
  E:/courses/University_courses/Design_Automation/project/project_2/project_2.srcs/sources_1/imports/code/BCD_adder.vhd
  E:/courses/University_courses/Design_Automation/project/project_2/project_2.srcs/sources_1/imports/code/N_digit_BCD_adder.vhd
  E:/courses/University_courses/Design_Automation/project/project_2/project_2.srcs/sources_1/imports/code/BCD_1x8_multiplier.vhd
  E:/courses/University_courses/Design_Automation/project/project_2/project_2.srcs/sources_1/imports/code/BCD_8x8_multiplier.vhd
}
synth_design -top BCD_8x8_multiplier -part xc7vx485tffg1761-2
write_checkpoint -noxdef BCD_8x8_multiplier.dcp
catch { report_utilization -file BCD_8x8_multiplier_utilization_synth.rpt -pb BCD_8x8_multiplier_utilization_synth.pb }
