# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/courses/University/Design_Automation/project/phase_four/phase_four.cache/wt [current_project]
set_property parent.project_path D:/courses/University/Design_Automation/project/phase_four/phase_four.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  D:/courses/University/Design_Automation/project/phase_four/phase_four.srcs/sources_1/new/divider.vhd
  D:/courses/University/Design_Automation/project/phase_four/phase_four.srcs/sources_1/new/BCDtoBin.vhd
  D:/courses/University/Design_Automation/project/phase_four/phase_four.srcs/sources_1/new/BCD_divider.vhd
  D:/courses/University/Design_Automation/project/phase_four/phase_four.srcs/sources_1/new/BinToBCD.vhd
  D:/courses/University/Design_Automation/project/phase_four/phase_four.srcs/sources_1/new/TB.vhd
}
synth_design -top BCD_divider -part xc7vx485tffg1157-1
write_checkpoint -noxdef BCD_divider.dcp
catch { report_utilization -file BCD_divider_utilization_synth.rpt -pb BCD_divider_utilization_synth.pb }
