# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.cache/wt} [current_project]
set_property parent.project_path {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.srcs/sources_1/imports/sim_1/new/full_adder.vhd}
  {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.srcs/sources_1/imports/sim_1/new/half_adder.vhd}
  {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.srcs/sources_1/imports/sim_1/new/multiplier.vhd}
  {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.srcs/sources_1/imports/sim_1/new/BinaryToBCD.vhd}
  {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.srcs/sources_1/imports/sim_1/new/BCD_multiplier.vhd}
  {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.srcs/sources_1/imports/sim_1/imports/new/BCD_adder.vhd}
  {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.srcs/sources_1/imports/sim_1/imports/new/BCD_1x8_multiplier.vhd}
  {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.srcs/sources_1/imports/sim_1/imports/new/N_digit_BCD_adder.vhd}
  {D:/courses/University courses/Design Automation/Homeworks/project/phase_one/phase_one.srcs/sources_1/imports/sim_1/imports/new/BCD_8x8_multiplier.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top BCD_8x8_multiplier -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef BCD_8x8_multiplier.dcp

catch { report_utilization -file BCD_8x8_multiplier_utilization_synth.rpt -pb BCD_8x8_multiplier_utilization_synth.pb }
