# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/courses/University courses/Design Automation/Homeworks/HW3/codes/HW3/HW3.cache/wt} [current_project]
set_property parent.project_path {D:/courses/University courses/Design Automation/Homeworks/HW3/codes/HW3/HW3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/courses/University courses/Design Automation/Homeworks/HW3/codes/HW3/HW3.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/courses/University courses/Design Automation/Homeworks/HW3/codes/HW3/HW3.srcs/sources_1/new/average.vhd}
  {D:/courses/University courses/Design Automation/Homeworks/HW3/codes/HW3/HW3.srcs/sources_1/new/TB.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top TB -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef TB.dcp

catch { report_utilization -file TB_utilization_synth.rpt -pb TB_utilization_synth.pb }
